-- INSERT scripts for HeritageCity table
-- Generated from: api-colombia data - Pueblos patrimonio.csv

INSERT INTO "HeritageCity" ("Id", "Name", "Description", "CityId", "DepartmentId", "Image") VALUES
(1, 'Aguadas, Caldas', 'Ubicado en el Paisaje Cultural Cafetero y reconocido por la UNESCO como Patrimonio de la Humanidad en 2011, Aguadas se destaca por su riqueza cultural, artesanal y arquitectónica. Es un pueblo de profundas tradiciones, reflejadas en celebraciones como el Festival Nacional del Pasillo Colombiano y las Fiestas Patronales de la Inmaculada Concepción, que mantienen vivo su legado histórico y folclórico.', 338, 8, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/1.Aguadas_Caldas.jpg'),
(2, 'Barichara, Santander', 'Fundado en 1705, Barichara es un pueblo que transmite calma y tradición. Sus calles empedradas, casas blancas de tapia pisada, techos de barro y puertas de madera crean una armonía única que lo convierte en uno de los pueblos más bellos del país. Su Centro Histórico fue declarado Monumento Nacional en 1975 y hoy es reconocido como Bien de Interés Cultural.', 920, 28, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/2.Barichara_Santander.jpg'),
(3, 'Cienaga, Magdalena', 'Conocida como “la capital del realismo mágico”, Ciénaga ha sido una fuente de inspiración para grandes escritores, entre ellos Gabriel García Márquez. Su riqueza histórica y arquitectónica le valió la declaratoria como Patrimonio Cultural de Colombia en 1994, consolidándola como un lugar lleno de memoria, tradición y encanto.', 738, 20, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/3.Cienaga_Magdalena.jpg'),
(4, 'El jardin, Antioquia ', 'Conocido como “el pueblo más bonito de Antioquia”, El Jardín es un municipio del suroeste antioqueño rodeado de montañas, ríos y paisajes imponentes. Su historia está ligada a las antiguas haciendas agrícolas y ganaderas, tradición productiva que aún se mantiene y define su identidad.', 135, 2, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/4.El jardin_Antioquia.png'),
(5, 'Guadalajara de Buga, Valle del Cauca ', 'Fundado en 1573, Guadalajara de Buga es uno de los principales destinos de turismo religioso en Colombia. Cada año recibe miles de visitantes atraídos por la devoción al Santísimo Redentor, una imagen a la que se le atribuyen numerosos milagros. Su arquitectura y su historia reflejan la importancia cultural y espiritual que ha marcado al municipio a lo largo del tiempo.', 1095, 31, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/5.Guadalajara_de_Buga_Valle_del_Cauca.jpg'),
(6, 'Jerico, Antioquia ', 'Conocida como “La Atenas del Suroeste”, Jericó es un pueblo patrimonio desde 2013, reconocido por su riqueza histórica, cultural y religiosa. Fundado como municipio en 1850, su desarrollo urbano se organizó alrededor de la plaza principal, dedicada a la Virgen de Las Mercedes, reflejando la tradición y el orden de los pueblos antioqueños.', 68, 2, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/6.Jerico_Antioquia.jpg'),
(7, 'Mongui, Boyaca ', 'Conocido como “el pueblo más lindo de Boyacá”, Monguí fue declarado Pueblo Patrimonio en 2010. Sus calles empedradas y casas antiguas reflejan la herencia indígena y colonial que define su identidad. Además, es reconocido a nivel mundial por la elaboración artesanal de balones de fútbol, una tradición que, desde 1930, ha sido transmitida de generación en generación por las familias del municipio.', 268, 7, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/7.Mongui_Boyaca.jpg'),
(8, 'Honda, Tolima ', 'Conocida como “la ciudad de los puentes”, Honda es Pueblo Patrimonio desde 2010. Su importancia histórica se remonta al siglo XVI, cuando fue un punto clave para el comercio y la comunicación, al servir como principal vía de salida de la producción minera de la región.', 1043, 30, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/8.Honda_Tolima.jpg'),
(9, 'Playa de Belen, Norte de Santander ', 'Reconocido como “el pueblito más lindo de Norte de Santander” desde 1995, La Playa de Belén se destaca por su arquitectura colonial, paisajes montañosos y cultivos que enriquecen su entorno. Uno de sus mayores atractivos es el área natural de Los Estoraques, donde formaciones rocosas esculpidas por la naturaleza crean un paisaje único y sorprendente.', 852, 23, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/9.Playa_de_Belen_Norte_de_Santander.jpg'),
(10, 'Salamina, Caldas', 'Fundado en 1825, Salamina es Pueblo Patrimonio desde 2010 y se distingue por su valioso patrimonio arquitectónico, reconocido como Bien de Interés Cultural. Su herencia cultural, la gastronomía típica, las artesanías y el aroma del café hacen de este municipio un destino acogedor y lleno de tradición, donde los visitantes disfrutan de la calidez de su gente y de paisajes inolvidables.', 356, 8, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/10.Salamina_Caldas.jpg'),
(11, 'San Juan de Giron, Santander ', 'Ubicado a pocos minutos del Aeropuerto Internacional Palonegro, Girón se distingue por su arquitectura de herencia española, con casas de bahareque y tapia pisada, tejas de barro y fachadas blancas. Este conjunto urbano, que evoca su pasado colonial, fue declarado Monumento Nacional en 1963 y hoy es reconocido como Bien de Interés Cultural.', 946, 28, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/11.San_Juan_de_Giron_Santander.jpg'),
(12, 'Villa de Guaduas, Cundinamarca ', 'Pueblo Patrimonio desde 2010, Villa de Guaduas conserva una arquitectura que refleja la historia de Colombia. Fundado en 1572 y ubicado sobre el antiguo Camino Real que unía Honda con Santa Fe, fue un punto clave en el desarrollo colonial del país. Además, es reconocido como la tierra natal de Policarpa Salavarrieta, heroína de la independencia.', 556, 15, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/12.Villa_de_Guaduas_Cundinamarca.jpg'),
(13, 'Santa Cruz de Lorica, Cordoba', 'Pueblo Patrimonio desde 2010, Santa Cruz de Lorica es conocida como la “Tierra de aguas encontradas”. Su arquitectura se distingue por la mezcla de estilos republicanos, vernáculos y mudéjares, con claras influencias andaluzas y árabes, reflejo de su riqueza cultural e histórica.', 506, 14, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/13.Santa_Cruz_de_Lorica_Cordoba.jpg'),
(14, 'Santa Cruz de Mompox, Bolivar ', 'Pueblo Patrimonio desde 2010, Santa Cruz de Mompox, conocida como “la tierra de Dios”, es uno de los conjuntos coloniales mejor conservados del país. Declarada Monumento Nacional en 1959 y Patrimonio de la Humanidad por la UNESCO en 1995, su arquitectura de templos, capillas y casas tradicionales se integra armoniosamente con el paisaje del río Magdalena.', 182, 6, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/14.Santa_Cruz_de_Mompox_Bolivar.jpg'),
(15, 'Santa Fe de Antioquia, Antioquia', 'Conocida como “el más bello relicario de la Colonia” en Antioquia, Santa Fe de Antioquia se distingue por su arquitectura colonial, calles empedradas e imponentes iglesias. Es considerada la cuna del departamento, ya que allí se establecieron los primeros templos y núcleos sociales que dieron origen a la identidad antioqueña, marcando profundamente la historia y las tradiciones de la región.', 125, 2, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/15.Santa_Fe_de_Antioquia_Antioquia.jpg'),
(16, 'Villa de Leyva, Boyaca', 'Villa de Leyva conserva uno de los conjuntos coloniales mejor preservados del país, con calles empedradas, fachadas blancas y una arquitectura que refleja su historia y vitalidad actual. Declarada Monumento Nacional en 1954 y hoy Bien de Interés Cultural, se destaca por su amplia plaza principal y sus paisajes únicos, que incluyen zonas desérticas ideales para la observación astronómica.', 326, 7, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/16.Villa_de_Leyva_Boyaca.jpg'),
(17, 'El Socorro, Santander ', 'Pueblo Patrimonio desde 2014, El Socorro es uno de los municipios más antiguos del país y un escenario clave de la historia de Colombia. Fundado en 1683, fue protagonista de hechos trascendentales como la Insurrección de los Comuneros en 1781 y la firma del Acta de Independencia Nacional, que marcaron el camino hacia la libertad del país.', 979, 28, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/17.El_Socorro_Santander.jpg'),
(18, 'Pore, Casanare', 'Designado Pueblo Patrimonio en 2018, Pore es un municipio del norte de Casanare que conserva calles empedradas y construcciones coloniales llenas de encanto. Más allá de su arquitectura, su mayor valor está en la historia, pues fue cuna de la independencia y, durante diez meses, capital de la República, un legado que llena de orgullo a los llaneros y define la identidad del municipio.', 386, 10, 'https://apicolombiastorage.blob.core.windows.net/heritagecity/18.Pore_Casanare.jpg');

-- Reset sequence to continue from the last ID
SELECT setval(pg_get_serial_sequence('"HeritageCity"', 'Id'), (SELECT MAX("Id") FROM "HeritageCity"));
